-- ============================================================
-- Photuna — Migration 013: Private Storage + Signed URLs
--
-- Makes the studiophotuna Storage bucket private so that files
-- are no longer publicly accessible via predictable URLs.
-- Operators access files through short-lived signed URLs
-- generated by the booth app at upload time.
--
-- IMPORTANT: After running this migration, deploy the updated
-- uploadSessionImages.js which calls createSignedUrl() instead
-- of getPublicUrl(). Existing public URLs in the galleries table
-- will stop working. Run the refresh_gallery_signed_urls() function
-- (or wait for the nightly cron) to regenerate them.
-- ============================================================


-- ============================================================
-- 1. Make the bucket private
-- ============================================================

UPDATE storage.buckets
SET public = false
WHERE name = 'studiophotuna';


-- ============================================================
-- 2. Storage RLS — drop old implicit-public policies
-- Supabase creates implicit policies when a bucket is public.
-- Now that the bucket is private we define explicit policies.
-- ============================================================

-- Allow authenticated operators to read and create signed URLs for session files.
-- Path convention: {eventId}/{sessionId}/...
-- We match on the session_id component against galleries.owner_user_id.
-- Note: signed URL access is cryptographic and does not go through RLS —
-- this policy only controls direct authenticated API calls (e.g. createSignedUrl).
DROP POLICY IF EXISTS "Operators read own session files" ON storage.objects;
CREATE POLICY "Operators read own session files"
  ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'studiophotuna'
    AND (
      -- Match via galleries.owner_user_id (populated since migration 008)
      EXISTS (
        SELECT 1 FROM public.galleries g
        WHERE g.session_id = (string_to_array(name, '/'))[2]
          AND g.owner_user_id = auth.uid()
      )
      -- Also allow if galleries row exists but owner_user_id not yet set
      -- (legacy sessions uploaded before migration 008)
      OR EXISTS (
        SELECT 1 FROM public.galleries g
        WHERE g.session_id = (string_to_array(name, '/'))[2]
          AND g.owner_user_id IS NULL
          AND auth.uid() IS NOT NULL
      )
    )
  );

-- Allow authenticated operators to upload files.
DROP POLICY IF EXISTS "Operators upload own session files" ON storage.objects;
CREATE POLICY "Operators upload own session files"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'studiophotuna'
  );

-- Service role has full access (used by booth app backend and cron cleanup).
DROP POLICY IF EXISTS "Service role full access studiophotuna" ON storage.objects;
CREATE POLICY "Service role full access studiophotuna"
  ON storage.objects FOR ALL
  TO service_role
  USING (bucket_id = 'studiophotuna')
  WITH CHECK (bucket_id = 'studiophotuna');


-- ============================================================
-- 3. Store storage paths alongside signed URLs
-- Add a path column to galleries so we can refresh signed URLs
-- without having to parse them from the URL string.
-- ============================================================

ALTER TABLE public.galleries
  ADD COLUMN IF NOT EXISTS final_path       text,
  ADD COLUMN IF NOT EXISTS final_video_path text,
  ADD COLUMN IF NOT EXISTS photo_paths      text[],
  ADD COLUMN IF NOT EXISTS urls_expire_at   timestamptz;


-- ============================================================
-- 4. refresh_gallery_signed_urls()
-- Regenerates signed URLs for galleries whose signed URLs are
-- within 7 days of expiry. Called nightly by pg_cron.
-- NOTE: Signed URL generation is done client-side via the
-- Supabase JS SDK. This function marks galleries as needing
-- refresh; the booth app refreshes on next gallery open.
-- ============================================================

CREATE OR REPLACE FUNCTION public.mark_galleries_for_url_refresh()
RETURNS int
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  marked int;
BEGIN
  -- Mark galleries whose signed URLs expire within 7 days as needing refresh
  WITH updated AS (
    UPDATE public.galleries
    SET urls_expire_at = NULL
    WHERE urls_expire_at IS NOT NULL
      AND urls_expire_at < now() + interval '7 days'
      AND archived_at IS NULL
    RETURNING id
  )
  SELECT count(*) INTO marked FROM updated;
  RETURN marked;
END;
$$;

SELECT cron.schedule(
  'photuna-mark-url-refresh',
  '30 1 * * *',
  $$SELECT public.mark_galleries_for_url_refresh()$$
);
